[FlatcoinVault]
proxy = "0x95Fa1ddc9a78273f795e67AbE8f1Cd2Cd39831fF"
implementation = "0x1F1A5f8c2d133b0c663cf85943B8E73ec143DB16"
proxyAdmin = "0x264964dB3B22b6a7aFBb2b923c0Cfe12096b3bD2"

[LeverageModule]
proxy = "0xdB0Cd65dcc7fE07003cE1201f91E1F966fA95768"
implementation = "0xaeB1E6aA19E8FB5BFBe6397F7cf48738e4A441ea"
proxyAdmin = "0x0CA7EaC3479a3D957b9DfFB3a8cD9BDF55c24A19"

[StableModule]
proxy = "0xb95fB324b8A2fAF8ec4f76e3dF46C718402736e2"
implementation = "0x3eAf69667707dC0Cf21419e6f2dF2626DD0ba501"
proxyAdmin = "0xEde01651Ab3E7c382B191Bba55d5f24384Ab1354"

[DelayedOrder]
proxy = "0x6D857e9D24a7566bB72a3FB0847A3E0e4E1c2879"
implementation = "0xe8621FC3F7A7e8E5CE046C764f68F9aaa637f244"
proxyAdmin = "0x3dA17F59ac1Cdd4Dfa994caC1BA6bF9117cEbaf0"

[OracleModule]
proxy = "0xAba633927BD8622FBBDd35D291A914c2fDAaE1Ff"
implementation = "0xaa13767088E946196e12eC3cE0B0b87CEf987BA3"
proxyAdmin = "0x2c08BFF48718889c9d8496fACB454FbF86f99C31"

[LiquidationModule]
proxy = "0x981a29dC987136d23dF5a0f67d86f428Fb40E8Aa"
implementation = "0x6A021Ad8E67B4591846eD1fedE864C94F76f2717"
proxyAdmin = "0x4fA83ECb257E3Fcb54683C7EA61128cD76f60Ed7"

[PointsModule]
proxy = "0x59525b9b23ADc475EF91d98dAe06B568BA574Ce5"
implementation = "0x3DDe914ABEBd96C4607F9E5CfA82815e73e75EE1"
proxyAdmin = "0xcAa5209ea295931Cf04051845C91f873459D5Fcb"

[LimitOrder]
proxy = "0x3FC737910B83381FD8288fD6c6d33Dacdf05307B"
implementation = "0x03DCbF85Ab96123F791DDF8475AB8e0D59b33aFb"
proxyAdmin = "0xef3Bd40258a8902e73B5C84A063160C750fcB7f0"

[KeeperFee]
contract = "0xAFf9F159bfe4870f2Dc12675da27059fd2b31A6c"

[Viewer]
contract = "0x509b85EEF0df77992b29aeDdD22C7119Db87ce16"

[ETHCrossAggregator]
contract = "0xbe1551fB22F8b877EDF3731CEc6FF703E720Fb85"
